/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BteaFIuRd4a
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function mcq() {
  return (
    <div className="bg-white p-8 max-w-3xl mx-auto space-y-8">
      <div className="flex justify-between items-center mb-4">
        <Button variant="ghost" className="p-1">
          <ChevronLeftIcon className="w-6 h-6" />
          <span>Previous Set</span>
        </Button>
        <Button variant="ghost" className="p-1">
          <span>Next Set</span>
          <ChevronRightIcon className="w-6 h-6" />
        </Button>
      </div>
      <h1 className="text-3xl font-bold mb-4">Quiz Instructions</h1>
      <div className="space-y-8">
        <div className="p-6 border border-gray-200 rounded-md space-y-4 dark:border-gray-800">
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1">
                <FlagIcon className="w-6 h-6" />
              </Button>
              <h2 className="text-xl font-semibold">Question 1</h2>
            </div>
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1 group relative">
                <InfoIcon className="w-6 h-6" />
                <div className="hidden group-hover:block absolute z-10 w-48 bg-white shadow-lg p-2 rounded-md">
                  <p className="text-base">Difficulty level: 10</p>
                </div>
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsUpIcon className="w-6 h-6" />
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsDownIcon className="w-6 h-6" />
              </Button>
            </div>
          </div>
          <div className="mb-8 space-y-2">
            <p className="text-base">Of the following name/symbol combinations of elements, which one is WRONG?</p>
          </div>
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <input type="radio" id="q1a1" name="question1" className="mr-2" />
              <label htmlFor="q1a1" className="flex items-center text-base">
                uranium/U
                <CircleCheckIcon className="w-6 h-6 text-green-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q1a2" name="question1" className="mr-2" />
              <label htmlFor="q1a2" className="flex items-center text-base">
                sulfur/S
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q1a3" name="question1" className="mr-2" />
              <label htmlFor="q1a3" className="flex items-center text-base">
                nitrogen/N
                <CircleCheckIcon className="w-6 h-6 text-green-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q1a4" name="question1" className="mr-2" />
              <label htmlFor="q1a4" className="flex items-center text-base">
                potassium/K
                <CircleCheckIcon className="w-6 h-6 text-green-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q1a5" name="question1" className="mr-2" />
              <label htmlFor="q1a5" className="flex items-center text-base">
                iron/I
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
          </div>
          <div className="mt-4 bg-green-100 border border-gray-200 border-green-500 text-green-700 p-4 rounded-md dark:border-gray-800">
            <p className="text-base">Explanation in HTML markdown like H1 tag and stuff.</p>
          </div>
        </div>
        <div className="p-6 border border-gray-200 rounded-md space-y-4 dark:border-gray-800">
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1">
                <FlagIcon className="w-6 h-6" />
              </Button>
              <h2 className="text-xl font-semibold">Question 2</h2>
            </div>
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1 group relative">
                <InfoIcon className="w-6 h-6" />
                <div className="hidden group-hover:block absolute z-10 w-48 bg-white shadow-lg p-2 rounded-md">
                  <p className="text-base">Difficulty level: 8</p>
                </div>
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsUpIcon className="w-6 h-6" />
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsDownIcon className="w-6 h-6" />
              </Button>
            </div>
          </div>
          <div className="mb-8 space-y-2">
            <p className="text-base">What is the chemical formula for water?</p>
          </div>
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <input type="radio" id="q2a1" name="question2" className="mr-2" />
              <label htmlFor="q2a1" className="flex items-center text-base">
                H2O
                <CircleCheckIcon className="w-6 h-6 text-green-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q2a2" name="question2" className="mr-2" />
              <label htmlFor="q2a2" className="flex items-center text-base">
                CO2
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q2a3" name="question2" className="mr-2" />
              <label htmlFor="q2a3" className="flex items-center text-base">
                NaCl
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q2a4" name="question2" className="mr-2" />
              <label htmlFor="q2a4" className="flex items-center text-base">
                CH4
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
          </div>
          <div className="mt-4 bg-green-100 border border-gray-200 border-green-500 text-green-700 p-4 rounded-md dark:border-gray-800">
            <p className="text-base">Explanation in HTML markdown like H1 tag and stuff.</p>
          </div>
        </div>
        <div className="p-6 border border-gray-200 rounded-md space-y-4 dark:border-gray-800">
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1">
                <FlagIcon className="w-6 h-6" />
              </Button>
              <h2 className="text-xl font-semibold">Question 3</h2>
            </div>
            <div className="flex items-center space-x-2">
              <Button variant="ghost" className="p-1 group relative">
                <InfoIcon className="w-6 h-6" />
                <div className="hidden group-hover:block absolute z-10 w-48 bg-white shadow-lg p-2 rounded-md">
                  <p className="text-base">Difficulty level: 6</p>
                </div>
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsUpIcon className="w-6 h-6" />
              </Button>
              <Button variant="ghost" className="p-1">
                <ThumbsDownIcon className="w-6 h-6" />
              </Button>
            </div>
          </div>
          <div className="mb-8 space-y-2">
            <p className="text-base">Which of the following is a noble gas?</p>
          </div>
          <div className="space-y-4">
            <div className="flex items-center space-x-2">
              <input type="radio" id="q3a1" name="question3" className="mr-2" />
              <label htmlFor="q3a1" className="flex items-center text-base">
                Oxygen
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q3a2" name="question3" className="mr-2" />
              <label htmlFor="q3a2" className="flex items-center text-base">
                Neon
                <CircleCheckIcon className="w-6 h-6 text-green-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q3a3" name="question3" className="mr-2" />
              <label htmlFor="q3a3" className="flex items-center text-base">
                Sodium
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
            <hr />
            <div className="flex items-center space-x-2">
              <input type="radio" id="q3a4" name="question3" className="mr-2" />
              <label htmlFor="q3a4" className="flex items-center text-base">
                Chlorine
                <CircleXIcon className="w-6 h-6 text-red-500 ml-2" />
              </label>
            </div>
          </div>
          <div className="mt-4 bg-green-100 border border-gray-200 border-green-500 text-green-700 p-4 rounded-md dark:border-gray-800">
            <p className="text-base">Explanation in HTML markdown like H1 tag and stuff.</p>
          </div>
        </div>
      </div>
      <div className="flex justify-between items-center mt-4">
        <Button variant="ghost" className="p-1">
          <ChevronLeftIcon className="w-6 h-6" />
          <span>Previous Set</span>
        </Button>
        <Button variant="ghost" className="p-1">
          <span>Next Set</span>
          <ChevronRightIcon className="w-6 h-6" />
        </Button>
      </div>
    </div>
  )
}

function ChevronLeftIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function CircleCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function CircleXIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>
  )
}


function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function InfoIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function ThumbsDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  )
}


function ThumbsUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
